version: 0.1

phases:
    build:
        commands:
            - npm install
            - npm run webpack
artifacts:
    files:
        - '*.html'
        - favicon.ico
        - main.css
        - css/*
        - dist/bundle.js
